version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    environment:
      - NODE_ENV=production
      - CI=false
      - PORT=3000
    depends_on:
      - product-service
      - user-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - mongo-data:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

volumes:
  mongo-data:
