version: '3.8'

services:
  mi-ecommerce:
    build: ./mi-ecommerce
    ports:
      - "3000:3000"
    volumes:
      - ./mi-ecommerce:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    environment:
      - NODE_ENV=production
      - CI=false
      - PORT=3000
    depends_on:
      - servicio-productos
      - servicio-usuarios
      - servicio-pedidos

  servicio-usuarios:
    build: ./servicio-usuarios
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  servicio-productos:
    build: ./servicio-productos
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  servicio-pedidos:
    build: ./servicio-pedidos
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - mongo-data:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

volumes:
  mongo-data:
